---
dependencies:
- name: "jenkins"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "0.32.9"
- name: "exposecontroller"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.3.95"
  alias: "jenkinsexpose"
- name: "exposecontroller"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "2.3.95"
  alias: "jenkinscleanup"
- name: "jx"
  alias: "jenkinstokenjob"
  repository: "http://chartmuseum.jenkins-x.io"
  version: "1.3.945"
  condition: "jenkinstokenjob.enabled"
