jenkinsexpose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    # use value of `path` to use path based ingress
    #config:
    #pathMode: "path"

jenkinscleanup:
  Args:
  - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded


jenkinstokenjob:
  enabled: true
  serviceaccount:
    enabled: true
  job:
    enabled: true
    annotations:
      helm.sh/hook: post-install,post-upgrade
      helm.sh/hook-delete-policy: hook-succeeded
  args:
  - "create"
  - "jenkins"
  - "token"
  - "--batch-mode"
  clusterrole:
    enabled: true
    rules:
    - apiGroups:
      - ""
      resources:
      - namespaces
      verbs:
      - get
      - list
      - watch
  role:
    enabled: true
    rules:
    - apiGroups:
      - ""
      resources:
      - configmaps
      - services
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - secrets
      verbs:
      - get
      - list
      - watch
      - create
      - update
    - apiGroups:
      - jenkins.io
      resources:
      - environments
      verbs:
      - get
      - list
      - watch

jenkins:
  rbac:
    install: true
    
  Master:
    ServiceType: ClusterIP

    ServiceLabels:
      jenkins.io/kind: "jenkins"

    ServiceAnnotations:
      #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/proxy-body-size: 500m"