expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
    # use value of `path` to use path based ingress
    #config:
    #pathMode: "path"

cleanup:
  Args:
  - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

jenkins:
  Master:
    ServiceType: ClusterIP

    ServiceLabels:
      jenkins.io/kind: "jenkins"

    ServiceAnnotations:
      #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/proxy-body-size: 500m"